---
- hosts: localhost
  connection: local
  collections:
    - vmware.alb
  tasks:
    - name: defining avi config
      set_fact:
        avi_role_config_log_mode: 'False'
        avi_config:
          vsvip:
            - name: vip1
              vrf_context_ref: /api/vrfcontext/?name=global
              tenant_ref: /api/tenant/?name=admin
              cloud_ref: /api/cloud/?name=Default-Cloud
              vip:
              - vip_id: '1'
                avi_allocated_fip: false
                auto_allocate_ip: false
                enabled: true
                auto_allocate_floating_ip: false
                avi_allocated_vip: false
                auto_allocate_ip_type: V4_ONLY
                ip_address:
                  type: V4
                  addr: 100.64.61.204
          pool:
            - name: poule1
              lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
              servers:
                - ip:
                   addr: 100.64.61.28
                   type: V4
          virtualservice:
            - name: service-1
              services:
                - port: 80
              pool_ref: /api/pool?name=poule1
              vsvip_ref: /api/vsvip/?name=vip1
              ssl_profile_ref: /api/sslprofile?name=System-Standard
              application_profile_ref: /api/applicationprofile?name=System-Secure-HTTP
              ssl_key_and_certificate_refs:
                - /api/sslkeyandcertificate?name=System-Default-Cert
    - name: Avi Application | Setup
      import_role:
        name: aviconfig
      vars:
        avi_config: "{{avi_config}}"
        avi_creds_file: "creds.yaml"
